baseURL = "https://isteves.netlify.com/"
languageCode = "en"
title = "Irene Steves"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
enableEmoji = true

# Disqus Username
# disqusShortname = "disqus_shortname"

# Google Analytics UA number
# googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Presentations"
  weight = 30
  identifier = "links"
  url = "/presentations/"

#[[menu.main]]
#  name = "Tags"
#  weight = 30
#  identifier = "tags"
#  url = "/tags/"

# Add your own params here
[params]
  author = "Irene Steves"
  avatar = "/img/avatar.jpg"
  seotitle = "Irene Steves"
  # subtitle = ""
  # description = ""
  paginate = 10

  # Choose your social networks
  # email = "name@domain.com"
  github = "isteves"
  twitter = "i_steves"
  
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "python"]
  highlightjsTheme = "atelier-cave-light"

  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

